# Generated by Django 4.1.2 on 2022-10-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=None, primary_key=True, serialize=False),
        ),
    ]
