# Generated by Django 5.0 on 2023-12-25 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_friends_delete_followercount_remove_like_id_and_more'),
    ]

    operations = [
    
      
    ]
