# Generated by Django 5.0 on 2023-12-25 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_followercount_remove_like_id'),
    ]

    operations = [
   
        migrations.AddField(
            model_name='profile',
            name='firstName',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastName',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='phoneNumber',
            field=models.IntegerField(default=None),
        ),
    ]
