# Generated by Django 5.0 on 2023-12-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_followercount_remove_like_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='firstName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phoneNumber',
            field=models.IntegerField(null=True),
        ),
    ]
