# Generated by Django 4.2.8 on 2023-12-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_profile_friends_friendship_delete_friends_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AddField(
            model_name='profile',
            name='profileID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
