# Generated by Django 4.2.8 on 2023-12-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_profile_gender_alter_profile_profileid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='friendshipID',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='like',
            name='likeID',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='messageID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notificationID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
