# Generated by Django 4.2.8 on 2023-12-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_comment_commentid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='likeDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=6, null=True),
        ),
    ]
